global:
  domain: e48aec5.kyma.ondemand.com
  imagePullSecret:
    name: container-registry
srv:
  bindings:
    db:
      fromSecret: cpapp-db
    auth:
      serviceInstanceName: xsuaa
  image:
    repository: shahbhat/cpapp-srv
    tag: latest
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health:
    liveness:
      path: /
    readiness:
      path: /
hana_deployer:
  image:
    repository: shahbhat/cpapp-hana-deployer
    tag: latest
  bindings:
    hana:
      fromSecret: cpapp-db
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
xsuaa:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    xsappname: cpapp
    tenant-mode: dedicated
    role-collections:
      - description: Manage Risks
        name: RiskManager
        role-template-references:
          - '$XSAPPNAME.RiskManager'
      - description: View Risks
        name: RiskViewer
        role-template-references:
          - '$XSAPPNAME.RiskViewer'
  config: xs-security.json
html5_apps_repo_host:
  serviceOfferingName: html5-apps-repo
  servicePlanName: app-host
html5_apps_deployer:
  cloudService: cpapp.service
  backendDestinations:
    cpapp-srv:
      service: srv
  image:
    repository: shahbhat/cpapp-html5-deployer
    tag: latest
  bindings:
    xsuaa:
      serviceInstanceName: xsuaa
    destination:
      serviceInstanceName: destination
    html5_apps_repo:
      serviceInstanceName: html5-apps-repo-host
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
destination:
  serviceOfferingName: destination
  servicePlanName: lite
  parameters:
    version: 1.0.0
    HTML5Runtime_enabled: true
